### ISSUE TITLE
Old Repository

### ISSUE THREAD

**Issue by SmplyVortexian** [etcherfx/precisionclient#2]
Why did you archive the old repository? also can i add a texture pack its called fruitful

**Comment by SmplyVortexian** [comment]
I have the epk file

**Comment by ZanderZhao2020** [comment]
> 

It's archived so that he can do an open-source rewrite

**Comment by ninefivenine** [comment]
Precision is currently being rewritten, please refrain from creating issues as this is not an issue.

**Comment by etcherfx** [comment]
@SmplyVortexian I have a slightly different pack format than the default because of precision client assets so other epks will not be very optimal because It will have missing textures. all items and all that stuff will work but the logo and precision client branding won't. for this reason, I won't be accepting plain epk files but will accept actual pack textures in the lwjgl-rundir/packs folder. you can do all this when I finish rewriting precision client. I will also add contributing guidelines.

**Comment by SmplyVortexian** [comment]
So you can only add .zip files?
